language: node_js
node_js:
  - 7
script:
  -
deploy:
  provider: firebase
  token:
    secure: xG4ffYC8WJTSvVQHkR4455KiuCdR+7WWhLKnHi9R2rvmSpnK1PDz308ebrErupKPDd/J+8VwXZjlT8j2UCueV1ltUSLvpjFkE2uYvh1PVq4rfNcSsH/SkxHAanjsLDY0sqKGx9l3oWTDPk9W9THfrvFoW+e838RE3QZR6BiLdi0nGnCNbxx7V76KA5KrqLrGkUekmoszalW/yepA6jpXIMPevK7a30k39mWLaMGjf8s7SI+PjgbP8iUYex4E2pSksty1thIyM4r5xVoa+XofborA3uI86OIFLWIrRJPyQqQX6a/bQWjTEl2RCGOhN6VEcLf0qzVJLl0fp3uric3/ej8TuxLz5n1U54O11R6w685VbsowTvWd3wTFOpHFQVWT5WsRk8MWWD40AKUBouQToTr42dzyY4CTJeWDg0vMJ9lOW1MrITxw3ap9IiI2Xsid4J4jYtGPFmCZSFFW51wTBEHtsjLpoAG1Z5ML5PnZg2HivWctxdkKxmtb8zT+xqwz4mc4vMc2iKO0Gx5nRONTFoxDDuKElUfY6JL8hwnSqyoJcyE2YaaCXZemN/3cpCTF8d/JttuUvM+vpndLofjJ0rrFchYwOnymz8eIlBar5X1HL+bdNMRI51/aCW8WGsjF48MKe8PWeG/cBk6pbj3P6JUbty0iFwmzPJr9z58nnZU=
